/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AnimateCanvas: typeof import('./components/animateCanvas.vue')['default']
    AnimateLoading: typeof import('./components/animateLoading.vue')['default']
    CustomMessageBox: typeof import('./components/CustomMessageBox/CustomMessageBox.vue')['default']
    CustomSlider: typeof import('./components/CustomSlider.vue')['default']
    CustomSliderLabel: typeof import('./components/CustomSliderLabel.vue')['default']
    MacroButton: typeof import('./components/MacroButton.vue')['default']
    MacroButtonItem: typeof import('./components/MacroButtonItem.vue')['default']
    MouseButton: typeof import('./components/MouseButton.vue')['default']
    MouseButtonCascader: typeof import('./components/MouseButtonCascader.vue')['default']
    MouseButtonCascaderItem: typeof import('./components/MouseButtonCascaderItem.vue')['default']
    MouseButtonItem: typeof import('./components/MouseButtonItem.vue')['default']
    MouseCarouseItem: typeof import('./components/MouseCarouseItem.vue')['default']
    ProfileItem: typeof import('./components/ProfileItem.vue')['default']
    ProfileList: typeof import('./components/ProfileList.vue')['default']
    README: typeof import('./components/README.md')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheCounter: typeof import('./components/TheCounter.vue')['default']
    TheFooter: typeof import('./components/TheFooter.vue')['default']
    TheInput: typeof import('./components/TheInput.vue')['default']
  }
}
