/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...all]': RouteRecordInfo<'/[...all]', '/:all(.*)', { all: ParamValue<true> }, { all: ParamValue<false> }>,
    '/about': RouteRecordInfo<'/about', '/about', Record<never, never>, Record<never, never>>,
    '/hid/[name]': RouteRecordInfo<'/hid/[name]', '/hid/:name', { name: ParamValue<true> }, { name: ParamValue<false> }>,
    '/hid/settings': RouteRecordInfo<'/hid/settings', '/hid/settings', Record<never, never>, Record<never, never>>,
    '/hid/v10': RouteRecordInfo<'/hid/v10', '/hid/v10', Record<never, never>, Record<never, never>>,
    '/hid/v11': RouteRecordInfo<'/hid/v11', '/hid/v11', Record<never, never>, Record<never, never>>,
    '/hid/v8': RouteRecordInfo<'/hid/v8', '/hid/v8', Record<never, never>, Record<never, never>>,
    '/hid/v9': RouteRecordInfo<'/hid/v9', '/hid/v9', Record<never, never>, Record<never, never>>,
    '/mouse-pairing': RouteRecordInfo<'/mouse-pairing', '/mouse-pairing', Record<never, never>, Record<never, never>>,
    '/README': RouteRecordInfo<'/README', '/README', Record<never, never>, Record<never, never>>,
    '/upload-update-package': RouteRecordInfo<'/upload-update-package', '/upload-update-package', Record<never, never>, Record<never, never>>,
  }
}
